// GENERATED by scripts/sync-core.mjs from mcp/src/pap-core.ts — do not edit here.
/**
 * PAP core — shared by the MCP server / CLI (Node) and the phone PWA + relay (browser / Next.js).
 * Source of truth: mcp/src/pap-core.ts. web/src/lib/pap-core.ts is a copy made by
 * `node scripts/sync-core.mjs` (CI fails if they drift). Keep this file self-contained:
 * no relative imports, only `viem`, `@noble/curves` and WebCrypto (globalThis.crypto).
 *
 * Secrets are sealed in two layers with ECIES over secp256k1 (the curve both the agent
 * identity key and the phone's EVM key already use):
 *
 *   stored = ECIES(ownerPub, { name, agent, inner: ECIES(agentPub, { name, agent, secret }) })
 *
 * The phone peels the outer layer only after Face ID and hands `inner` to the agent; the
 * agent opens it with its identity key. The relay only ever sees ciphertext, the phone never
 * sees the plaintext, and neither layer opens for a different agent or secret name (both are
 * bound as AES-GCM additional data).
 */
import { secp256k1 } from "@noble/curves/secp256k1";
import {
  bytesToHex,
  hashMessage,
  hashTypedData,
  hexToBytes,
  isAddress,
  keccak256,
  recoverPublicKey,
  stringToHex,
  type Address,
  type Hex,
} from "viem";

// ───────────────────────────── ECIES ─────────────────────────────

export type Envelope = { v: 1; alg: "secp256k1-hkdf-sha256-aes256gcm"; epk: Hex; iv: Hex; ct: Hex };

const utf8 = new TextEncoder();
const fromUtf8 = new TextDecoder();
const subtle = () => globalThis.crypto.subtle;
const buf = (b: Uint8Array) => b as Uint8Array<ArrayBuffer>;

async function aesKey(shared: Uint8Array, epk: Uint8Array) {
  const ikm = await subtle().importKey("raw", buf(shared.slice(1)), "HKDF", false, ["deriveKey"]);
  return subtle().deriveKey(
    { name: "HKDF", hash: "SHA-256", salt: buf(epk), info: utf8.encode("pap-ecies-v1") },
    ikm,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}

/** Encrypt `plaintext` to an uncompressed or compressed secp256k1 public key. */
export async function eciesEncrypt(recipientPub: Hex, plaintext: Uint8Array, aad: string): Promise<Envelope> {
  const eph = secp256k1.utils.randomPrivateKey();
  const epk = secp256k1.getPublicKey(eph, true);
  const key = await aesKey(secp256k1.getSharedSecret(eph, hexToBytes(recipientPub), true), epk);
  const iv = globalThis.crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(
    await subtle().encrypt({ name: "AES-GCM", iv, additionalData: utf8.encode(aad) }, key, buf(plaintext))
  );
  return { v: 1, alg: "secp256k1-hkdf-sha256-aes256gcm", epk: bytesToHex(epk), iv: bytesToHex(iv), ct: bytesToHex(ct) };
}

export async function eciesDecrypt(privateKey: Hex, env: Envelope, aad: string): Promise<Uint8Array> {
  if (env?.v !== 1 || env.alg !== "secp256k1-hkdf-sha256-aes256gcm") throw new Error("unsupported envelope");
  const epk = hexToBytes(env.epk);
  const key = await aesKey(secp256k1.getSharedSecret(hexToBytes(privateKey), epk, true), epk);
  try {
    return new Uint8Array(
      await subtle().decrypt(
        { name: "AES-GCM", iv: buf(hexToBytes(env.iv)), additionalData: utf8.encode(aad) },
        key,
        buf(hexToBytes(env.ct))
      )
    );
  } catch {
    throw new Error("decryption failed (wrong key, wrong agent/name, or tampered blob)");
  }
}

// ───────────────────────────── Layered seal ─────────────────────────────

export const SECRET_NAME = /^[a-z0-9][a-z0-9_-]{0,63}$/;
export function assertSecretName(name: string) {
  if (!SECRET_NAME.test(name)) throw new Error("secret name must be 1-64 chars of a-z 0-9 _ - (lowercase)");
}

const aad = (layer: "owner" | "agent", agent: Address, name: string) => `pap:${layer}:${agent.toLowerCase()}:${name}`;
const encodeEnv = (e: Envelope) => JSON.stringify(e);
const decodeEnv = (s: string) => JSON.parse(s) as Envelope;

export type SealTarget = { name: string; agent: Address; agentPub: Hex; ownerPub: Hex };

/** Laptop / browser: seal a secret so it opens only with the phone's peel + the agent's key. */
export async function sealSecret(secret: string, t: SealTarget): Promise<string> {
  assertSecretName(t.name);
  if (!isAddress(t.agent)) throw new Error("bad agent address");
  const inner = await eciesEncrypt(
    t.agentPub,
    utf8.encode(JSON.stringify({ v: 1, name: t.name, agent: t.agent.toLowerCase(), secret })),
    aad("agent", t.agent, t.name)
  );
  const outer = await eciesEncrypt(
    t.ownerPub,
    utf8.encode(JSON.stringify({ v: 1, name: t.name, agent: t.agent.toLowerCase(), inner: encodeEnv(inner) })),
    aad("owner", t.agent, t.name)
  );
  return encodeEnv(outer);
}

/** Phone: remove the owner layer. Returns the inner blob, still encrypted to the agent. */
export async function peelOwnerLayer(blob: string, ownerPk: Hex, expect: { name: string; agent: Address }): Promise<string> {
  const pt = JSON.parse(fromUtf8.decode(await eciesDecrypt(ownerPk, decodeEnv(blob), aad("owner", expect.agent, expect.name))));
  if (pt.name !== expect.name || pt.agent !== expect.agent.toLowerCase()) throw new Error("sealed for a different agent or name");
  return pt.inner as string;
}

/** Agent: open the inner layer with the identity key. */
export async function openAgentLayer(inner: string, agentPk: Hex, expect: { name: string; agent: Address }): Promise<string> {
  const pt = JSON.parse(fromUtf8.decode(await eciesDecrypt(agentPk, decodeEnv(inner), aad("agent", expect.agent, expect.name))));
  if (pt.name !== expect.name || pt.agent !== expect.agent.toLowerCase()) throw new Error("sealed for a different agent or name");
  return pt.secret as string;
}

export const blobHash = (blob: string) => keccak256(stringToHex(blob));

// ───────────────────────────── Keys ─────────────────────────────

/** Compressed public key of a private key (33 bytes, 0x02/0x03…). */
export const publicKeyOf = (privateKey: Hex): Hex => bytesToHex(secp256k1.getPublicKey(hexToBytes(privateKey), true));

/** Public key behind an EIP-191 personal_sign signature (what the relay already verifies). */
export const publicKeyFromMessageSig = (message: string, signature: Hex): Promise<Hex> =>
  recoverPublicKey({ hash: hashMessage(message), signature });

// ───────────────────────────── EIP-712 ─────────────────────────────

export const PAP_CHAIN_ID = 133;

export const papDomain = (verifyingContract: Address) =>
  ({ name: "PAP", version: "1", chainId: PAP_CHAIN_ID, verifyingContract }) as const;

export const papTypes = {
  /** Agent → relay: "let me read secret `name`, for `reason`". */
  RevealRequest: [
    { name: "agent", type: "address" },
    { name: "name", type: "string" },
    { name: "reason", type: "string" },
    { name: "nonce", type: "string" },
    { name: "expiry", type: "uint64" },
  ],
  /** Phone → relay: "I released secret `name` of `agent` as the blob with hash `resultHash`". */
  RevealApproval: [
    { name: "requestId", type: "string" },
    { name: "agent", type: "address" },
    { name: "name", type: "string" },
    { name: "resultHash", type: "bytes32" },
  ],
  /** Sealer → relay: store `blobHash` as secret `name` of `agent`, readable `maxReads` times until `expiry`. */
  SealRequest: [
    { name: "agent", type: "address" },
    { name: "name", type: "string" },
    { name: "blobHash", type: "bytes32" },
    { name: "maxReads", type: "uint256" },
    { name: "expiry", type: "uint64" },
    { name: "nonce", type: "string" },
  ],
} as const;

export type RevealRequestMsg = { agent: Address; name: string; reason: string; nonce: string; expiry: bigint };
export type RevealApprovalMsg = { requestId: string; agent: Address; name: string; resultHash: Hex };
export type SealRequestMsg = { agent: Address; name: string; blobHash: Hex; maxReads: bigint; expiry: bigint; nonce: string };

type Primary = keyof typeof papTypes;
type MsgOf<P extends Primary> = P extends "RevealRequest"
  ? RevealRequestMsg
  : P extends "RevealApproval"
    ? RevealApprovalMsg
    : SealRequestMsg;

export function typedData<P extends Primary>(verifyingContract: Address, primaryType: P, message: MsgOf<P>) {
  return { domain: papDomain(verifyingContract), types: papTypes, primaryType, message } as const;
}

/** Recover the signer's public key from an EIP-712 signature (also gives its address). */
export function publicKeyFromTypedSig<P extends Primary>(
  verifyingContract: Address,
  primaryType: P,
  message: MsgOf<P>,
  signature: Hex
): Promise<Hex> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return recoverPublicKey({ hash: hashTypedData(typedData(verifyingContract, primaryType, message) as any), signature });
}

/** JSON-safe form of a typed message (bigint → string) for relay bodies. */
export const wire = <T extends Record<string, unknown>>(m: T) =>
  Object.fromEntries(Object.entries(m).map(([k, v]) => [k, typeof v === "bigint" ? v.toString() : v])) as {
    [K in keyof T]: T[K] extends bigint ? string : T[K];
  };

// ───────────────────────────── On-chain scopes ─────────────────────────────

/** AgentPassport scope for secret `name` = keccak256("secret:" + name). */
export const secretScope = (name: string) => keccak256(stringToHex(`secret:${name}`));

/** `record()` ref for a reveal, so each read is a distinct, traceable stamp. */
export const revealRef = (requestId: string) => keccak256(stringToHex(`pap:reveal:${requestId}`));
