// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";
import {PassportRegistry} from "../src/PassportRegistry.sol";
import {IdentityRegistry} from "../src/IdentityRegistry.sol";
import {ReputationRegistry} from "../src/ReputationRegistry.sol";

contract PassportTest is Test {
    Groth16Verifier verifier;
    PassportRegistry passport;
    IdentityRegistry identity;
    ReputationRegistry reputation;

    address issuer = makeAddr("issuer");
    address agentOwner = makeAddr("agentOwner");
    address client = makeAddr("client");

    // Fixture generated by scripts/gen-fixture.mjs (real Groth16 proof from zkpjwt-core circuit)
    uint256[2] pA;
    uint256[2][2] pB;
    uint256[2] pC;
    uint256 root;
    uint256 setSize;

    bytes32 constant SERVICE = keccak256("oracle.example");
    bytes32 constant NULLIFIER = keccak256("agent-2:oracle.example");

    function setUp() public {
        verifier = new Groth16Verifier();
        passport = new PassportRegistry(verifier, issuer);
        identity = new IdentityRegistry();
        reputation = new ReputationRegistry(identity);

        string memory json = vm.readFile("test/fixtures/proof.json");
        // parseJson encodes arrays as dynamic; copy into the static tuples the verifier expects.
        uint256[] memory a = vm.parseJsonUintArray(json, ".pA");
        uint256[] memory b0 = vm.parseJsonUintArray(json, ".pB[0]");
        uint256[] memory b1 = vm.parseJsonUintArray(json, ".pB[1]");
        uint256[] memory c = vm.parseJsonUintArray(json, ".pC");
        pA = [a[0], a[1]];
        pB = [[b0[0], b0[1]], [b1[0], b1[1]]];
        pC = [c[0], c[1]];
        root = vm.parseJsonUint(json, ".root");
        setSize = vm.parseJsonUint(json, ".setSize");
    }

    // ---- ERC-8004 minimal registries ----

    function test_registerAndFeedback() public {
        vm.prank(agentOwner);
        uint256 id = identity.register("ipfs://agent.json");
        assertEq(id, 1);
        assertEq(identity.ownerOf(1), agentOwner);
        assertEq(identity.getAgentWallet(1), agentOwner);
        assertEq(identity.tokenURI(1), "ipfs://agent.json");

        vm.prank(client);
        reputation.giveFeedback(1, 90, 0, "quality", "", "", "", bytes32(0));
        vm.prank(client);
        reputation.giveFeedback(1, 80, 0, "quality", "", "", "", bytes32(0));

        (uint64 count, int128 sum,) = reputation.getSummary(1, new address[](0), "", "");
        assertEq(count, 2);
        assertEq(sum, 170);
    }

    function test_selfFeedbackReverts() public {
        vm.prank(agentOwner);
        identity.register("");
        vm.prank(agentOwner);
        vm.expectRevert(ReputationRegistry.SelfFeedback.selector);
        reputation.giveFeedback(1, 100, 0, "", "", "", "", bytes32(0));
    }

    function test_onlyOwnerSetsURI() public {
        vm.prank(agentOwner);
        identity.register("");
        vm.prank(client);
        vm.expectRevert(IdentityRegistry.NotAgentOwner.selector);
        identity.setAgentURI(1, "x");
    }

    // ---- Passport ----

    function test_validProofPasses() public {
        vm.prank(issuer);
        passport.publishRoot(root, setSize);
        assertTrue(passport.checkPassport(pA, pB, pC, root));

        passport.verifyPassport(pA, pB, pC, root, SERVICE, NULLIFIER);
        assertTrue(passport.nullifierUsed(SERVICE, NULLIFIER));
    }

    function test_unknownRootReverts() public {
        vm.expectRevert(PassportRegistry.UnknownRoot.selector);
        passport.verifyPassport(pA, pB, pC, root, SERVICE, NULLIFIER);
    }

    function test_replayReverts() public {
        vm.prank(issuer);
        passport.publishRoot(root, setSize);
        passport.verifyPassport(pA, pB, pC, root, SERVICE, NULLIFIER);
        vm.expectRevert(PassportRegistry.NullifierAlreadyUsed.selector);
        passport.verifyPassport(pA, pB, pC, root, SERVICE, NULLIFIER);
    }

    function test_sameNullifierOtherServiceOk() public {
        vm.prank(issuer);
        passport.publishRoot(root, setSize);
        passport.verifyPassport(pA, pB, pC, root, SERVICE, NULLIFIER);
        passport.verifyPassport(pA, pB, pC, root, keccak256("other"), NULLIFIER);
    }

    function test_tamperedProofFails() public {
        vm.prank(issuer);
        passport.publishRoot(root, setSize);
        uint256[2] memory badA = [pA[0] + 1, pA[1]];
        assertFalse(passport.checkPassport(badA, pB, pC, root));
        vm.expectRevert(PassportRegistry.InvalidProof.selector);
        passport.verifyPassport(badA, pB, pC, root, SERVICE, NULLIFIER);
    }

    function test_onlyIssuerPublishes() public {
        vm.expectRevert();
        passport.publishRoot(root, setSize);
    }
}
