#!/usr/bin/env node
/**
 * Copies mcp/src/pap-core.ts (source of truth) to web/src/lib/pap-core.ts.
 *   node scripts/sync-core.mjs          # write
 *   node scripts/sync-core.mjs --check  # exit 1 if the copy is stale (CI)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const src = new URL("../mcp/src/pap-core.ts", import.meta.url);
const dst = new URL("../web/src/lib/pap-core.ts", import.meta.url);
const banner = "// GENERATED by scripts/sync-core.mjs from mcp/src/pap-core.ts — do not edit here.\n";
const want = banner + readFileSync(src, "utf8");

if (process.argv.includes("--check")) {
  if (!existsSync(dst) || readFileSync(dst, "utf8") !== want) {
    console.error("web/src/lib/pap-core.ts is stale — run: node scripts/sync-core.mjs");
    process.exit(1);
  }
  console.log("pap-core in sync");
} else {
  writeFileSync(dst, want);
  console.log("wrote web/src/lib/pap-core.ts");
}
